name: Publish Modeller as GitHub Page

on:
  push:
    branches: [ main, dev** ]
    tags: [ v** ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: |
          git clone https://github.com/FREAS-tools/freas-bpmn4frss-library.git
          cd freas-bpmn4frss-library/src
          npm install
          npm link
          cd ../..
          npm install
          npm link freas-bpmn4frss-library
      - name: Build Vite app
        env:
          VITE_PORT: 8080
          VITE_HOST: 0.0.0.0
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
